#spring.application.name=BacktestingStrategies
#alphavantage.api.key=XKHV09MRZB6O2W90
#
#
## set the MYSQL db username and all the relevant properties overhere
#spring.datasource.url=jdbc:mysql://localhost:3306/backtest
#spring.datasource.username=root
#spring.datasource.password=pass@123
#
## JPA / Hibernate
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true



spring:
  application:
    name: BacktestingStrategies

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true

alphavantage:
  api:
    key: ${ALPHAVANTAGE_API_KEY}


server:
    tomcat:
      basedir: ${java.io.tmpdir}/tomcat